[package]
name = "weenachuangkud/fastcast2"
description = "An improved version of FastCast with Parallel scripting, more extensions, and statically typed"
author = "Mawin Chuangkud"
version = "0.1.3" # bumped for publish
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE", "README.md"]

[dependencies]
