[package]
name = "mawin/benchmark"
description = "Some benchmarking for FastCast2"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ByteNet = "ffrostflame/bytenet@0.4.6"
