name: Run tests

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rokit
        run: |
          curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | sh
          echo "$HOME/.rokit/bin" >> "$GITHUB_PATH"

      - name: Install tools
        run: rokit install

      - name: Run tests
        run: npm test
